# Generated by Django 4.0 on 2023-05-27 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_code_user_is_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('USER', 'user'), ('CONSULTANT', 'consultant')], default='USER', max_length=10),
        ),
    ]
