# Generated by Django 4.0 on 2023-05-27 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='listener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listener', to='api.user'),
        ),
        migrations.AlterField(
            model_name='room',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='type_of',
            field=models.CharField(blank=True, choices=[('OTA', 'Open to all'), ('IO', 'Invite only')], default='OTA', max_length=3, null=True),
        ),
    ]
